version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: beers
      POSTGRES_USER: beer
      POSTGRES_PASSWORD: 1234

  app:
    image: craftbeer
    container_name: craftbeer
    restart: always
    depends_on:
      - db
    ports:
      - "9000:9000"